package com.gxaedu.crm.pojo;

public interface BuMenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int insert(BuMen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int insertSelective(BuMen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    BuMen selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BuMen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BuMen record);
}